import { chromium } from 'playwright';
const assert=(x,m)=>{if(!x)throw new Error(m)};
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
await page.goto('http://127.0.0.1:8765/index.html',{waitUntil:'networkidle'});
await page.waitForFunction(()=>window.__driftQA);
const initial=await page.evaluate(()=>window.__driftQA.state());
assert(initial.phaseName==='launch','bad initial phase');
await page.screenshot({path:'01-initial.png'});
await page.evaluate(()=>window.__driftQA.start());
await page.waitForFunction(()=>window.__driftQA.state().phaseName==='flick',{timeout:1800});
await page.waitForTimeout(180);
const flick=await page.evaluate(()=>window.__driftQA.state());
assert(flick.slip>.35,'flick must create visible slip angle');
assert(flick.yaw>0.5,'flick must create strong yaw');
await page.screenshot({path:'02-flick.png'});
await page.waitForFunction(()=>window.__driftQA.state().phaseName==='counter',{timeout:1800});
await page.waitForTimeout(100);
const counter=await page.evaluate(()=>window.__driftQA.state());
assert(counter.steer<0,'counter phase must visibly countersteer');
await page.screenshot({path:'03-counter.png'});
await page.waitForFunction(()=>window.__driftQA.state().phaseName==='exit',{timeout:1800});
const exit=await page.evaluate(()=>window.__driftQA.state());
await page.screenshot({path:'04-catch.png'});
await page.waitForFunction(()=>window.__driftQA.state().done===true,{timeout:2500});
const result=await page.evaluate(()=>({state:window.__driftQA.state(),history:window.__driftQA.history()}));
await page.screenshot({path:'05-exited.png'});
const duration=result.state.completedAt-result.state.startedAt;
assert(duration<2200,'drift maneuver too slow: '+duration);
assert(result.state.maxSlip>.5,'drift never reached strong slip');
assert(Math.abs(result.state.heading)<.14,'final heading not caught');
assert(result.state.slip<.18,'final velocity not aligned');
let maxStep=0;for(let i=1;i<result.history.length;i++){const a=result.history[i-1],b=result.history[i];maxStep=Math.max(maxStep,Math.hypot(b.x-a.x,b.y-a.y))}
assert(maxStep<7,'teleport-like displacement');
console.log(JSON.stringify({status:'PASS',initial,flick,counter,exit,final:result.state,durationMs:+duration.toFixed(1),maxSlipDeg:+(result.state.maxSlip*180/Math.PI).toFixed(1),maxYaw:+result.state.maxYaw.toFixed(2),maxStepPx:+maxStep.toFixed(2),samples:result.history.length},null,2));
await browser.close();