import { chromium } from 'playwright';
const assert=(x,m)=>{if(!x)throw new Error(m)};
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
await page.goto('http://127.0.0.1:8765/index.html',{waitUntil:'networkidle'});
await page.waitForFunction(()=>window.__reverseCutbackQA);
const initial=await page.evaluate(()=>window.__reverseCutbackQA.state());
assert(initial.phaseName==='reverse_straight','bad initial phase');
assert(Math.abs(initial.heading-Math.PI/2)<.01,'car must start facing dead end');
await page.screenshot({path:'01-initial.png'});
await page.evaluate(()=>window.__reverseCutbackQA.start());
await page.waitForFunction(()=>window.__reverseCutbackQA.state().phaseName==='reverse_swing',{timeout:4000});
const reverse=await page.evaluate(()=>window.__reverseCutbackQA.state());
assert(reverse.speed<0,'reverse phase must use negative velocity');
await page.screenshot({path:'02-reverse-swing.png'});
await page.waitForFunction(()=>window.__reverseCutbackQA.state().phaseName==='shift',{timeout:4000});
const shift=await page.evaluate(()=>window.__reverseCutbackQA.state());
await page.screenshot({path:'03-shift.png'});
await page.waitForFunction(()=>window.__reverseCutbackQA.state().phaseName==='forward_countersteer',{timeout:4000});
await page.waitForTimeout(650);
const forward=await page.evaluate(()=>window.__reverseCutbackQA.state());
assert(forward.speed>0,'forward phase must use positive velocity');
assert(forward.steer<0,'countersteer must reverse steering sign');
await page.screenshot({path:'04-forward-turn.png'});
await page.waitForFunction(()=>window.__reverseCutbackQA.state().done===true,{timeout:6000});
const result=await page.evaluate(()=>({state:window.__reverseCutbackQA.state(),history:window.__reverseCutbackQA.history()}));
await page.screenshot({path:'05-exited.png'});
assert(result.state.x>452,'car did not exit');
assert(Math.abs(result.state.heading)<.18,'car did not straighten toward exit');
assert(result.state.maxSteerSeen<=30*Math.PI/180+.001,'steer clamp exceeded');
assert(result.history.some(x=>x.speed<0),'no reverse samples');
assert(result.history.some(x=>x.speed>0),'no forward samples');
assert(result.history.some(x=>x.phase==='shift'),'no shift phase');
let maxStep=0;
for(let i=1;i<result.history.length;i++){const a=result.history[i-1],b=result.history[i];maxStep=Math.max(maxStep,Math.hypot(b.x-a.x,b.y-a.y))}
assert(maxStep<5,'teleport-like displacement');
const durationMs=result.state.completedAt-result.state.startedAt;
assert(durationMs<3800,'maneuver still too slow: '+durationMs+'ms');
console.log(JSON.stringify({status:'PASS',initial,reverse,shift,forward,final:result.state,durationMs:+durationMs.toFixed(1),maxStepPx:+maxStep.toFixed(2),samples:result.history.length},null,2));
await browser.close();